#!/usr/bin/env just --justfile

list:
  just --list

build-local:
  #!/bin/bash
  set -euo pipefail
  cd {{justfile_directory()}}
  if [ ! -d build ]; then
    meson setup build
  fi
  (cd build && ninja)

build: build-local

test: build-local
  #!/bin/bash
  set -euo pipefail
  cd {{justfile_directory()}}/build
  meson test
