[package]
name = "dis86"
version = "0.1.0"
edition = "2021"

[features]
default = ["emu86"]
emu86 = ["dep:sdl2"]

[dependencies]
pico-args = "0.5.0"
itertools = "0.12.1"
static_assertions = "1.1.0"
libc = "0.2"
sdl2 = { version = "0.38", features = ["use-pkgconfig", "unsafe_textures"], optional = true }

[build-dependencies]
cc = "1.0.87"

[[bin]]
name = "dis86"
path = "src/bin/dis86.rs"

[[bin]]
name = "mzfile"
path = "src/bin/mzfile.rs"

[[bin]]
name = "emu86"
path = "src/bin/emu86.rs"
required-features = ["emu86"]

[[bin]]
name = "emu86_validator"
path = "src/bin/emu86_validator.rs"
required-features = ["emu86"]